version: "3"

services:
  app:
    build:
      context: ./backend/app
    container_name: app
    ports:
      - "8000:8000"

  tests:
    build:
      context: ./tests
    depends_on:
      - app
    environment:
      - FASTAPI_HTTP_HOST=http://app:8000
      - FASTAPI_WS_HOST=ws://app:8000
    volumes:
      - ./reports:/tests/reports
